/fonts/*.woff
  Access-Control-Allow-Origin: *
  Content-Type: application/font-woff

/fonts/*.woff2
  Access-Control-Allow-Origin: *
  Content-Type: application/font-woff2

/fonts/*.ttf
  Access-Control-Allow-Origin: *
  Content-Type: application/font-ttf

/fonts/*.eot
  Access-Control-Allow-Origin: *
  Content-Type: application/font-eot

/fonts/*.svg
  Access-Control-Allow-Origin: *
  Content-Type: application/font-svg

/fonts/*.otf
  Access-Control-Allow-Origin: *
  Content-Type: application/font-otf